### ISSUE TITLE
Bot won't start

### ISSUE THREAD

**Issue by alsoGAMER** [An0nimia/DeezloaderRMX_bot#2]
Traceback (most recent call last):
  File "/home/downloaderbot/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./dwsongs.py", line 31, in <module>
    downloa = deezloader.Login(setting.username, setting.password)
  File "/home/downloaderbot/.local/lib/python3.5/site-packages/deezloader/__init__.py", line 52, in __init__
    check = self.req.post("http://www.deezer.com/ajax/gw-light.php", params).json()['results']['checkFormLogin']
  File "/home/downloaderbot/.local/lib/python3.5/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/downloaderbot/.local/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/downloaderbot/.local/lib/python3.5/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/downloaderbot/.local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/downloaderbot/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/downloaderbot/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)

**Comment by An0nimia** [comment]
Have you inserted correct credentials?

**Comment by alsoGAMER** [comment]
yes, of course

**Comment by An0nimia** [comment]
Have you all libraries updated?

**Comment by An0nimia** [comment]
Have you all libraries updated?

**Comment by alsoGAMER** [comment]
Do you mean pip dependencies?

**Comment by An0nimia** [comment]
@alsoGAMER Yes

**Comment by alsoGAMER** [comment]
Yes, i've also tried to reinstall it, but nothing changes

**Comment by An0nimia** [comment]
@alsoGAMER Strange, do you use linux?

**Comment by alsoGAMER** [comment]
Yes, of course

**Comment by An0nimia** [comment]
@alsoGAMER What distro?

**Comment by alsoGAMER** [comment]
Debian 9.7 x64

**Comment by An0nimia** [comment]
@alsoGAMER Strange can you try a virtual machine?

**Comment by alsoGAMER** [comment]
I've tried on my production vps, so tecnically is a vm
On the test server a raspberry pi 3b with raspbian 9.5 it works

**Comment by An0nimia** [comment]
@alsoGAMER Type this pip3 show requests and see if they are the same version

**Comment by alsoGAMER** [comment]
It print anyting

**Comment by An0nimia** [comment]
@alsoGAMER WTF?

**Comment by alsoGAMER** [comment]
![image](https://user-images.githubusercontent.com/35269770/51706143-d8813e80-201d-11e9-9de6-4ab7d6add645.png)

**Comment by An0nimia** [comment]
@alsoGAMER pip3 show requests, no pip3 show request

**Comment by alsoGAMER** [comment]
Name: requests
Version: 2.21.0
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache 2.0
Location: /home/downloaderbot/.local/lib/python3.5/site-packages
Requires: certifi, idna, chardet, urllib3

**Comment by An0nimia** [comment]
@alsoGAMER And on raspberry and debian?

**Comment by alsoGAMER** [comment]
> Name: requests
> Version: 2.21.0
> Summary: Python HTTP for Humans.
> Home-page: http://python-requests.org
> Author: Kenneth Reitz
> Author-email: [me@kennethreitz.org](mailto:me@kennethreitz.org)
> License: Apache 2.0
> Location: /home/downloaderbot/.local/lib/python3.5/site-packages
> Requires: certifi, idna, chardet, urllib3

This on production server, now i'll try on raspbian

**Comment by alsoGAMER** [comment]
On test server (raspbian):
Name: requests
Version: 2.21.0
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache 2.0
Location: /home/downloaderbot/.local/lib/python3.5/site-packages
Requires: certifi, urllib3, chardet, idna
